baseURL = "https://dwalkr.github.io/sawmill/"
languageCode = "en-us"
theme = "sawmill-landing"
title = "Videogames PEI"
[Author]
name = "DJ Walker"
[[menu.main]]
name = "View on Github"
url = "https://github.com/dwalkr/sawmill"
weight = 10
[params]
logo = "/uploads/2018/05/27/videogamespei_logo.png"
