baseURL = "https://jamespohalloran.github.io/videogames-pei-landing/"
languageCode = "en-us"
theme = "sawmill-landing"
title = "Videogames PEI"
[Author]
name = "James O'Halloran"
[[menu.main]]
[params]
logo = "/uploads/2018/05/28/videogamespei_logo.png"
